# $OpenBSD$

COMMENT =	entity-component-system game library
CATEGORIES =	games

GH_ACCOUNT =	skypjack
GH_PROJECT =	entt
GH_TAGNAME =	v3.2.0

HOMEPAGE =	https://github.com/skypjack/entt/wiki
MAINTAINER =	Brian Callahan <bcallah@openbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

MODULES =	devel/cmake

NO_TEST =	Yes

.include <bsd.port.mk>
