# $OpenBSD$

COMMENT =	utility to return resolved physical paths
DISTNAME =	realpath-5.2.1
CATEGORIES =	sysutils

HOMEPAGE =	https://www.dragonflybsd.org/
MAINTAINER =	Brian Callahan <bcallah@openbsd.org>

# BSD
PERMIT_PACKAGE =	Yes

WANTLIB += c

MASTER_SITES =	https://mirrors.nycbug.org/pub/distfiles/

.include <bsd.port.mk>
