# $OpenBSD$

COMMENT =	fast C++ logging library
CATEGORIES =	textproc

GH_ACCOUNT =	gabime
GH_PROJECT =	spdlog
GH_TAGNAME =	v1.4.1

MAINTAINER =	Your Name <you@example.com>

# MIT
PERMIT_PACKAGE =	Yes

# C++11
COMPILER =	base-clang ports-gcc

MODULES =	devel/cmake

.include <bsd.port.mk>
