# $OpenBSD$

COMMENT =	plain but clever development environment
DISTNAME =	dce-0.17
CATEGORIES =	editors x11

HOMEPAGE =	https://www.jmos.net/software/dce.shtml
MAINTAINER =	Brian Callahan <bcallah@openbsd.org>

# BSD
PERMIT_PACKAGE =	Yes

#WANTLIB += X11 c curses

MASTER_SITES =	https://www.jmos.net/download/

.include <bsd.port.mk>
