# $OpenBSD$

V =		1.0
COMMENT =	size profiler for binaries
DISTNAME =	bloaty-${V}
EXTRACT_SUFX =	.tar.bz2
CATEGORIES =	sysutils

HOMEPAGE =	https://github.com/google/bloaty
MAINTAINER =	Your Name <you@example.com>

# Apache 2.0
PERMIT_PACKAGE =	Yes

MASTER_SITES =	https://github.com/google/bloaty/releases/download/v${V}/

MODULES =	devel/cmake

.include <bsd.port.mk>
