# $OpenBSD$

COMMENT =	GNU software administration system
DISTNAME =	swbis-1.13.2
CATEGORIES =	sysutils

HOMEPAGE =	https://www.gnu.org/software/swbis/
MAINTAINER =	Brian Callahan <bcallah@openbsd.org>

# GPLv3+
PERMIT_PACKAGE =	Yes

#WANTLIB += c

MASTER_SITES =	${MASTER_SITE_GNU:=swbis/}

DEBUG_PACKAGES =	${BUILD_PACKAGES}

CONFIGURE_STYLE =	gnu

.include <bsd.port.mk>
