# $OpenBSD$

COMMENT =	utility that prints a sequence of numbers
DISTNAME =	seq-12.0pl20180501
CATEGORIES =	sysutils textproc

HOMEPAGE =	https://www.freebsd.org/
MAINTAINER =	Brian Callahan <bcallah@openbsd.org>

# BSD
PERMIT_PACKAGE =	Yes

WANTLIB += c m

MASTER_SITES =	https://mirrors.nycbug.org/pub/distfiles/

.include <bsd.port.mk>
