# $OpenBSD$

COMMENT =	ImGui widget for displaying flame graphs
CATEGORIES =	games x11

GH_ACCOUNT =	bwrsandman
GH_PROJECT =	imgui-flame-graph
GH_TAGNAME =	v1.00

MAINTAINER =	Your Name <you@example.com>

# MIT
PERMIT_PACKAGE =	Yes

#WANTLIB += ${COMPILER_LIBCXX} GL GLU ICE SM X11 Xext c m

# C++17
COMPILER =	base-clang ports-gcc

MODULES =	devel/cmake

.include <bsd.port.mk>
