# $OpenBSD$

COMMENT =	lightweight C++ command line option parser
CATEGORIES =	devel

GH_ACCOUNT =	jarro2783
GH_PROJECT =	cxxopts
GH_TAGNAME =	v2.2.0

MAINTAINER =	Your Name <you@example.com>

# MIT
PERMIT_PACKAGE =	Yes

# C++11
COMPILER =	base-clang ports-gcc

MODULES =	devel/cmake

.include <bsd.port.mk>
