# $OpenBSD$

COMMENT =	arbitrary precision calculator from NetBSD
DISTNAME =	nbc-1.0pl20180502
CATEGORIES =	math

HOMEPAGE =	https://www.netbsd.org/

# BSD
PERMIT_PACKAGE =	Yes

WANTLIB += c curses edit

MASTER_SITES =	https://mirrors.nycbug.org/pub/distfiles/

CONFIGURE_STYLE =	simple

.include <bsd.port.mk>
