# $OpenBSD$

COMMENT =	yaegi is another elegant Go interpreter

MODGO_MODNAME =	github.com/containous/yaegi
MODGO_VERSION =	v0.8.6

DISTNAME =	yaegi-${MODGO_VERSION}

CATEGORIES =	lang

HOMEPAGE =	https://github.com/containous/yaegi

# Apache 2.0
PERMIT_PACKAGE =	Yes

WANTLIB += c pthread

MODULES =		lang/go

.include <bsd.port.mk>
