# $OpenBSD$

COMMENT =	GTK stylesheet from elementary OS
PKGNAME =	${DISTNAME:S/^/elementary-/}

GH_PROJECT =	stylesheet
GH_TAGNAME =	5.4.2

# GPLv3+
PERMIT_PACKAGE =	Yes

BUILD_DEPENDS =	devel/gettext,-tools \
		www/sassc

.include <bsd.port.mk>
