# $OpenBSD$

COMMENT =	standard lockfile library
CATEGORIES =	mail

GH_ACCOUNT =	miquels
GH_PROJECT =	liblockfile
GH_TAGNAME =	v1.16

MAINTAINER =	Brian Callahan <bcallah@openbsd.org>

# GPLv2+
PERMIT_PACKAGE =	Yes

WANTLIB += c

CONFIGURE_STYLE =	gnu

FAKE_FLAGS =	mandir="${DESTDIR}${PREFIX}/man"

NO_TEST =	Yes

.include <bsd.port.mk>
