# $OpenBSD: Makefile,v 1.27 2019/07/12 20:49:08 sthen Exp $

COMMENT=	module to calculate SHA digests

MODULES=	cpan
DISTNAME=	Digest-SHA-6.02
CATEGORIES=	security

# Artistic licence
PERMIT_PACKAGE=	Yes

WANTLIB += c perl

.include <bsd.port.mk>
